# Generated by Django 2.1 on 2018-09-27 07:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('crop_grown', models.CharField(blank=True, max_length=50, null=True)),
                ('sowing_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertiliser', models.CharField(blank=True, max_length=100, null=True)),
                ('days_after_sowing', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, choices=[('1', 'Ton'), ('2', 'Kilo-gram'), ('3', 'gram'), ('4', 'mili-litre'), ('5', 'litre')], max_length=10, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Farmer'),
        ),
    ]
